### ISSUE TITLE
Structures spawning too high

### ISSUE THREAD

**Issue by MilitaryFool** [Hir0shiyt/Trident-Crafting-And-Structures-Forge#1]
The structures in my world generated by this mod are spawning in the air, not in the water or under water, I this normal behavior?
![2021-11-21_11 50 16](https://user-images.githubusercontent.com/62164836/142773294-c7178b46-cac2-4662-869a-f8473a34a964.png)

**Comment by Hir0shiyt** [comment]
This is meant to be like this, it's a mutated **falling** giant trident

**Comment by Hir0shiyt** [comment]
The other one in the back, i'll fix that rn
